version: '3'
services:
  app:
    build: .
    container_name: CIR-PROJECT-FRONTEND
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
      
    command: npm run dev
